# Generated by Django 4.2.4 on 2024-04-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_taskstatus_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cnpj_cpf', models.TextField(max_length=14)),
                ('ie_rg', models.TextField(max_length=20)),
                ('logradouro', models.TextField()),
                ('numero', models.TextField()),
                ('complemento', models.TextField(null=True)),
                ('cidade', models.TextField()),
                ('estado', models.TextField(max_length=2)),
                ('cep', models.TextField(max_length=9)),
                ('ibge', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.employee')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.enterprise')),
            ],
        ),
    ]
