# Generated by Django 4.2.4 on 2024-05-14 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('xml', models.TextField()),
                ('status', models.CharField(choices=[('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=20)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('destinatario_cnpj', models.CharField(max_length=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensagem_retorno', models.TextField(blank=True, null=True)),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfe_emitente', to='companies.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoDetalheNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncm', models.CharField(max_length=20)),
                ('cest', models.CharField(blank=True, max_length=20, null=True)),
                ('unidade', models.CharField(max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='companies.nfe')),
            ],
        ),
    ]
