# Generated by Django 4.2.4 on 2024-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_client_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfe',
            old_name='destinatario_endereco',
            new_name='destinatario_bairro',
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_cep',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_cidade',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_complemento',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_estado',
            field=models.TextField(default='SP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_ibge',
            field=models.TextField(default='123456'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_logradouro',
            field=models.TextField(default='RUA TESTE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='destinatario_numero',
            field=models.TextField(default='RUA TESTE'),
            preserve_default=False,
        ),
    ]
