# Generated by Django 4.2.4 on 2024-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_rename_destinatario_endereco_nfe_destinatario_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='status',
            field=models.CharField(choices=[('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=255),
        ),
    ]
