# Generated by Django 4.2.4 on 2024-05-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_nfe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodetalhenfe',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
