# Generated by Django 4.2.4 on 2024-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_nfe_xml_alter_product_cest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
